module.exports = {
  Mango: [
    "MANGO",
    "MANGOS",
    "AMNGOS",
    "MANG",
    "MAN",
    "MA",
    "M",
    "FRUITS",
    "FRUIT",
  ],
  Apples: [
    "APPLE",
    "APPLES",
    "APPPLE",
    "APPPLES",
    "APPL",
    "APP",
    "AP",
    "A",
    "FRUITS",
    "FRUIT",
  ],
  BlueBerries: ["BlueBerries", "BlueBerry"],
  NodeBerry: ["NodeBerry", "NodeBerries"],
  Banana: ["Banana", "Bananas"],
  Onion: ["Onion", "Onions"],
  Potato: ["Potato", "Potatos"],
  Spinach: ["Spinach", "Spinaches"],
  Carrot: ["Carrot", "Carrots"],
  Brocolli: ["Brocolli", "Brocollis"],
  Capsicum: ["Capsicum", "Capsicums"],
  Pea: ["Pea", "Peas"],
};
